[package]

name = "mars-data"
version = "0.1.2"
authors = ["Conor Forde"]
edition = '2021'

license = "LGPL3"

repository = "https://www.github.com/Snowda/Mars-Data"

description = "Mars data parsing"
keywords = ["mars", "planet", "data"]

[dependencies]

# Astro data
astro = "2.0.0"

# JSON
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.93"

# Networking
reqwest = { version = "0.11", features = ["json", "gzip"] }

# Threading
tokio = { version = "1.27.0", features = ["full"] }

# Time library
chrono = "0.4"

# Two Line Elements
tletools = "0.1.0"

# SQL
# sqlx = "0.5.2"