[package]

name = "mars-data"
version = "0.1.3"
authors = ["Conor Forde"]
rust-version = "1.70.0"
edition = '2021'
repository = "https://www.github.com/Snowda/Mars-Data"

description = "Mars data parsing"
keywords = ["mars", "planet", "data"]

[dependencies]

# Astro data
astro = "2.0.0"

# JSON
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"

# Networking
reqwest = { version = "0.11.20", features = ["json", "gzip"] }

# Threading
tokio = { version = "1.35.1", features = ["full"] }

# Time library
chrono = "0.4.31"

# Two Line Elements
tletools = "0.1.0"

# SQL
# sqlx = "0.5.2"